{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "kaipo-client.fullname" . }}
  labels:
    {{- include "kaipo-client.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ .host }}`)
      kind: Rule
      services:
        - name: {{ include "kaipo-client.fullname" $ }}
          port: {{ $.Values.service.port }}
    {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}